name: Rodando Criando Indice Localizacao Imoveis Balneario Camboriu
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Balneario Camboriu"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: balneario_camboriu
      arquivo_rodando_imovel: balneario_camboriu_indice_localizacao.py