name: Rodando Coleta Viva Real Blumenau
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Blumenau"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel:  blumenau_coleta_dados_viva_real.py