name: Rodando Coleta Chave Mao Itapoa
on: 

    workflow_run:
        workflows: ["Rodando Coleta Viva Real Itapoa"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itapoa
      arquivo_rodando_imovel: itapoa_coleta_dados_chave_mao.py