name: Rodando Coleta Viva Real Jaragua do Sul
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Jaragua do Sul"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: jaragua
      arquivo_rodando_imovel:  jaragua_coleta_dados_viva_real.py