name: Rodando Criando Indice Localizacao Imoveis Joinville
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Joinville"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_criando_indice_localizacao.py