name: Rodando Coleta Chave Mao Balneario Camboriu
on: 

    workflow_run:
        workflows: ["Rodando Coleta Viva Real Balneario Camboriu"]
        types:
            - completed
    workflow_dispatch:  

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: balneario_camboriu
      arquivo_rodando_imovel:  balneario_camboriu_coleta_dados_chave_mao.py