name: Rodando Limpeza Imoveis Blumenau
on: 

    workflow_run:
        workflows: ["Rodando Juncao Dados Blumenau"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_limpando_dados.py
      cidade_limpeza: blumenau
      cidade_localizacao: Blumenau
      estado_limpeza: sc
      estado_localizacao: SC
      tipo_async : true