name: Rodando Coleta Chave Mao Blumenau
on:
  schedule:
    - cron: '0 9 4 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

jobs:
  coleta_chave_mao_blumenau_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_0_100.py
  
  coleta_chave_mao_blumenau_101_220:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_101_220.py

  coleta_chave_mao_blumenau_221_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_221_infinito.py