name: Rodando Coleta Chave Mao Blumenau
on:
  schedule:
    - cron: '0 9 4 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

jobs:
  coleta_chave_mao_blumenau_0_75:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_0_75.py
  
  coleta_chave_mao_blumenau_76_140:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_76_140.py

  coleta_chave_mao_blumenau_141_350:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_141_350.py

  coleta_chave_mao_blumenau_351_700:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_351_700.py

  coleta_chave_mao_blumenau_701_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: blumenau
      arquivo_rodando_imovel: blumenau_coleta_dados_chave_mao_701_infinito.py