name: Rodando Criando Indice Localizacao Curitiba
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Curitiba"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: curitiba
      arquivo_rodando_imovel: curitiba_criando_indice_localizacao.py