name: Rodando Otimizacao Melhores Modelos Curitiba
on: 
    workflow_run:
        workflows: ["Rodando Treinamento de Imoveis de Curitiba"]
        types:
            - completed
    workflow_dispatch:

jobs:
    treinamento_modelos_predicoes:
        uses: ./.github/workflows/pipeline_cidade_rodando.yml
        with:
            cidade_pasta: curitiba
            arquivo_rodando_imovel: curitiba_otimizando_melhores_modelos.py
            DATABRICKS_HOST: "https://dbc-ed602b14-1f14.cloud.databricks.com"
            LOCALIZAZAO_COMPLETA : "Curitiba, Parana, Brasil"
        secrets: inherit
