name: Rodando Coleta Zap Curitiba 1
on: 
  schedule:
    - cron: '0 9 14 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch:

jobs:
  coleta_zap_imoveis_0_50:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: curitiba
      arquivo_rodando_imovel: curitiba_coleta_dados_zap_imoveis_0_50.py

  coleta_zap_imoveis_51_80:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: curitiba
      arquivo_rodando_imovel: curitiba_coleta_dados_zap_imoveis_51_80.py
  
  coleta_zap_imoveis_81_110:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: curitiba
      arquivo_rodando_imovel: curitiba_coleta_dados_zap_imoveis_81_110.py

  coleta_zap_imoveis_111_140:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: curitiba
      arquivo_rodando_imovel: curitiba_coleta_dados_zap_imoveis_111_140.py

