name: Rodando Coleta Zap Imoveis Florianopolis
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9 1 1,2,3,4,5,6,7,8,9,10,11,12 *'  

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel:  florianopolis_coleta_dados_zap_imoveis.py