name: Rodando Limpeza Imoveis Florianopolis
on: 

  workflow_run:
    workflows: ["Rodando Juncao Dados Florianopolis"]
    types:
      - completed
  workflow_dispatch:

jobs:
  coleta_limpando_dados_itajai:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_limpando_dados.py
      cidade_limpeza: florianopolis
      cidade_localizacao: Florianopolis
      estado_limpeza: sc
      estado_localizacao: SC