name: Rodando Limpeza Imoveis Florianopolis
on: 

  workflow_run:
    workflows: ["Rodando Juncao Dados Florianopolis"]
    types:
      - completed
  workflow_dispatch:

jobs:
  coleta_limpando_dados_itajai_zap:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_limpando_dados_zap.py
      cidade_limpeza: florianopolis
      cidade_localizacao: Florianopolis
      estado_limpeza: sc
      estado_localizacao: SC
  
  coleta_limpando_dados_itajai_viva_real:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_limpando_dados_viva_real.py
      cidade_limpeza: florianopolis
      cidade_localizacao: Florianopolis
      estado_limpeza: sc
      estado_localizacao: SC
  
  coleta_limpando_dados_itajai_chave_mao:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_limpando_dados_chave_mao.py
      cidade_limpeza: florianopolis
      cidade_localizacao: Florianopolis
      estado_limpeza: sc
      estado_localizacao: SC