name: Rodando Coleta Zap Florianopolis 1
on: 
  schedule:
    - cron: '0 9 11 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch:

jobs:
  coleta_zap_imoveis_0_60:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_zap_imoveis_0_60.py

  coleta_zap_imoveis_61_80:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_zap_imoveis_61_80.py
  
  coleta_zap_imoveis_81_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_zap_imoveis_81_100.py

  coleta_zap_imoveis_101_130:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_zap_imoveis_101_130.py

