name: Rodando Coleta Viva Real Florianopolis 2
on: 
  workflow_run:
        workflows: ["Rodando Coleta Viva Real Florianopolis 1"]
        types:
            - completed
  workflow_dispatch:

jobs:
  coleta_viva_real_131_180:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_viva_real_131_180.py

  coleta_viva_real_181_250:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_viva_real_181_250.py
  
  coleta_viva_real_251_400:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_viva_real_251_400.py

  coleta_viva_real_401_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: florianopolis
      arquivo_rodando_imovel: florianopolis_coleta_dados_viva_real_401_infinito.py

