name: Rodando Coleta Viva Real Itajai
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Itajai"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itajai
      arquivo_rodando_imovel:  itajai_coleta_dados_viva_real.py