name: Rodando Coleta Chave Mao Itajai
on:
  schedule:
    - cron: '0 13 6 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

    

jobs:
  coleta_chave_mao_itajai_0_85:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itajai
      arquivo_rodando_imovel: itajai_coleta_dados_chave_mao_0_85.py
  
  coleta_chave_mao_itajai_86_170:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itajai
      arquivo_rodando_imovel: itajai_coleta_dados_chave_mao_86_170.py

  coleta_chave_mao_itajai_171_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itajai
      arquivo_rodando_imovel: itajai_coleta_dados_chave_mao_171_infinito.py