name: Rodando Criando Indice Localizacao Imoveis Itajai
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Itajai"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itajai
      arquivo_rodando_imovel: itajai_indice_localizacao.py