name: Rodando Treinamento de Imoveis de Itapoa
on: 
    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Itapoa"]
        types:
            - completed
    workflow_dispatch:

jobs:
    treinamento_modelos_predicoes:
        uses: ./.github/workflows/pipeline_cidade_rodando.yml
        with:
            cidade_pasta: itapoa
            arquivo_rodando_imovel: itapoa_melhores_configuraoes_modelo.py
            DATABRICKS_HOST: "https://dbc-ed602b14-1f14.cloud.databricks.com"
            LOCALIZAZAO_COMPLETA : "Itapoa, Santa Catarina, Brasil"
        secrets: inherit
