name: Rodando Limpeza Imoveis Itapema
on: 

    workflow_run:
        workflows: ["Rodando Coleta OLX Itapema"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itapema
      arquivo_rodando_imovel: itapema_limpando_dados.py
      cidade_limpeza: itapema
      cidade_localizacao: Itapema
      estado_limpeza: sc
      estado_localizacao: SC