name: Rodando Coleta Chave Mao Itapema
on:
  schedule:
    - cron: '0 9 11 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

jobs:
  coleta_chave_mao_itapema_0_110:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itapema
      arquivo_rodando_imovel: itapema_coleta_dados_chave_mao_0_110.py

  coleta_chave_mao_itapema_111_170:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itapema
      arquivo_rodando_imovel: itapema_coleta_dados_chave_mao_111_170.py

  coleta_chave_mao_itapema_171_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: itapema
      arquivo_rodando_imovel: itapema_coleta_dados_chave_mao_171_infinito.py