name: Rodando Otimizacao Melhores Modelos Jaragua
on: 
    workflow_run:
        workflows: ["Rodando Treinamento de Imoveis de Jaragua"]
        types:
            - completed
    workflow_dispatch:

jobs:
    treinamento_modelos_predicoes:
        uses: ./.github/workflows/pipeline_cidade_rodando.yml
        with:
            cidade_pasta: jaragua
            arquivo_rodando_imovel: jaragua_otimizando_melhores_modelos.py
            DATABRICKS_HOST: "https://dbc-ed602b14-1f14.cloud.databricks.com"
            LOCALIZAZAO_COMPLETA : "Jaragua do Sul, Santa Catarina, Brasil"
        secrets: inherit
