name: Rodando Coleta Viva Real Jaragua
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Jaragua"]
        types:
            - completed
    workflow_dispatch:

jobs:
  coleta_viva_real_jaragua_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: jaragua
      arquivo_rodando_imovel: jaragua_coleta_dados_viva_real_0_100.py
  
  coleta_viva_real_jaragua_101_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: jaragua
      arquivo_rodando_imovel: jaragua_coleta_dados_viva_real_101_infinito.py