name: Rodando Coleta Zap Imoveis Jaragua
on: 
    workflow_run:
        workflows: ["Rodando Coleta OLX Jaragua"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: jaragua
      arquivo_rodando_imovel:   jaragua_coleta_dados_zap_imoveis.py
  