name: "Avaliacao Flip Joinville -Bairro Centro (Batches 200-300)"
on:
  workflow_run:
    workflows: ["Avaliacao Flip Joinville -Bairro Centro (Batches 100-200)"]
    types:
      - completed
  workflow_dispatch:
jobs:
  batch_200_210:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "200"
      limite_superior: "210"
      bairro: "centro"
    secrets: inherit

  batch_210_220:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "210"
      limite_superior: "220"
      bairro: "centro"
    secrets: inherit

  batch_220_230:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "220"
      limite_superior: "230"
      bairro: "centro"
    secrets: inherit

  batch_230_240:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "230"
      limite_superior: "240"
      bairro: "centro"
    secrets: inherit

  batch_240_250:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "240"
      limite_superior: "250"
      bairro: "centro"
    secrets: inherit

  batch_250_260:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "250"
      limite_superior: "260"
      bairro: "centro"
    secrets: inherit

  batch_260_270:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "260"
      limite_superior: "270"
      bairro: "centro"
    secrets: inherit

  batch_270_280:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "270"
      limite_superior: "280"
      bairro: "centro"
    secrets: inherit

  batch_280_290:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "280"
      limite_superior: "290"
      bairro: "centro"
    secrets: inherit

  batch_290_300:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "290"
      limite_superior: "300"
      bairro: "centro"
    secrets: inherit
