name: Rodando Coleta Imovelweb Joinville
on: 
  schedule:
    - cron: '0 9 2 1,2,3,4,5,6,7,8,9,10,11,12 *'  # mesma data da junção: dia 2, 09:00
  workflow_run:
        workflows: ["Rodando Coleta Viva Real Joinville"]
        types:
            - completed
  workflow_dispatch:  

jobs:
  coleta_imovelweb_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_imovelweb_0_100.py

  coleta_imovelweb_101_200:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_imovelweb_101_200.py

  coleta_imovelweb_201_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_imovelweb_201_infinito.py
 

  