name: "Avaliacao Flip Joinville - Bairro Gloria (Batches 100-200)"
on:
  workflow_run:
    workflows: ["Avaliacao Flip Joinville - Bairro Gloria (Batches 0-100)"]
    types:
      - completed
  workflow_dispatch:
jobs:
  batch_100_110:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "100"
      limite_superior: "110"
      bairro: "gloria"
    secrets: inherit

  batch_110_120:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "110"
      limite_superior: "120"
      bairro: "gloria"
    secrets: inherit

  batch_120_130:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "120"
      limite_superior: "130"
      bairro: "gloria"
    secrets: inherit

  batch_130_140:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "130"
      limite_superior: "140"
      bairro: "gloria"
    secrets: inherit

  batch_140_150:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "140"
      limite_superior: "150"
      bairro: "gloria"
    secrets: inherit

  batch_150_160:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "150"
      limite_superior: "160"
      bairro: "gloria"
    secrets: inherit

  batch_160_170:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "160"
      limite_superior: "170"
      bairro: "gloria"
    secrets: inherit

  batch_170_180:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "170"
      limite_superior: "180"
      bairro: "gloria"
    secrets: inherit

  batch_180_190:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "180"
      limite_superior: "190"
      bairro: "gloria"
    secrets: inherit

  batch_190_200:
    uses: ./.github/workflows/joinville_avaliacao_flip_base.yml
    with:
      limite_inferior: "190"
      limite_superior: "200"
      bairro: "gloria"
    secrets: inherit
