name: Rodando Coleta Viva Real Joinville 0 90
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Joinville 181 Infinito"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel:  joinville_coleta_dados_viva_real_0_90.py