name: Coleta Joinville Paralela
on:
  schedule:
    - cron: '0 9 1 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch:

jobs:
  coleta_chave_mao_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_chave_mao_0_100.py

  coleta_chave_mao_101_200:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_chave_mao_101_200.py

  coleta_chave_mao_201_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_chave_mao_201_infinito.py

  coleta_olx_0_80:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_olx_0_80.py

  coleta_olx_81_150:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_olx_81_150.py

  coleta_olx_151_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_olx_151_infinito.py

  coleta_viva_real_0_90:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_viva_real_0_90.py

  coleta_viva_real_91_180:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_viva_real_91_180.py

  coleta_viva_real_181_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_viva_real_181_infinito.py

  coleta_zap_imoveis_0_90:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_zap_imoveis_0_90.py

  coleta_zap_imoveis_91_180:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_zap_imoveis_91_180.py

  coleta_zap_imoveis_181_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: joinville
      arquivo_rodando_imovel: joinville_coleta_dados_zap_imoveis_181_infinito.py
