name: Rodando Predicao Valores Joinville
on: 
    workflow_run:
        workflows: ["Rodando Otimizacao Melhores Modelos Joinville"]
        types:
            - completed
    workflow_dispatch:

jobs:
    treinamento_modelos_predicoes:
        uses: ./.github/workflows/pipeline_cidade_rodando.yml
        with:
            cidade_pasta: joinville
            arquivo_rodando_imovel: joinville_melhor_modelo_geral.py
            DATABRICKS_HOST: "https://dbc-ed602b14-1f14.cloud.databricks.com"
            LOCALIZAZAO_COMPLETA : "Joinville, Santa Catarina, Brasil"
        secrets: inherit