name: Pipeline Cidade

on:
  workflow_call:
    inputs:
      cidade_pasta:
        required: true
        type: string
      arquivo_rodando_imovel:
        required: true
        type: string
      headless:
        required: false
        type: boolean
        default: true
      max_concurrency_chave:
        required: false
        type: number
        default: 5
      max_concurrency_olx:
        required: false
        type: number
        default: 5
      max_concurrency_zap:
        required: false
        type: number
        default: 3
      cidade_limpeza:
        required: false 
        type: string
      cidade_localizacao:
        required: false
        type: string
      estado_limpeza:
        required: false
        type: string
      estado_localizacao:
        required: false
        type: string
      max_concurrency_localizacao:
        required: false
        type: number
        default: 20
      batch_limpeza:
        required: false
        type: number
        default: 10
      tipo_async:
        required: false
        type: boolean
        default: true
      BAIRRO:
        required: false
        type: string
      URL_TEMPLATE_CHAVES:
        required: false
        type: string
      URL_TEMPLATE_VIVAREAL:
        required: false
        type: string
      URL_TEMPLATE_OLX:
        required: false
        type: string
      URL_TEMPLATE_ZAP:
        required: false
        type: string
      FILTRO_BAIRRO:
        required: false
        type: string
      DATABRICKS_HOST:
        required: false
        default: "https://dbc-ed602b14-1f14.cloud.databricks.com"
        type: string
      LOCALIZAZAO_COMPLETA:
        required: false
        type: string
      INCLUIR_TOPICOS:
        required: false
        type: string
        default: "false"
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar o uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Criar ambiente virtual
        run: |
          uv venv

      - name: Instalar as bibliotecas
        run: |
          source .venv/bin/activate
          make uv_install

      - name: Instalar o Playwright
        run: |
          uv pip install -e .
          uv pip install playwright
          uv run playwright install --with-deps chromium

      - name: Rodar o código do imóvel
        if: ${{ inputs.arquivo_rodando_imovel != '' }}
        #run: uv run codigos_rodando/${{ inputs.cidade_pasta }}/${{ inputs.arquivo_rodando_imovel }}
        run: |
          # Define o caminho base: se BAIRRO existir, inclui na rota, senão usa apenas cidade_pasta
          CAMINHO_EXECUCAO="codigos_rodando/${{ inputs.cidade_pasta }}/${{ inputs.BAIRRO != '' && format('{0}/', inputs.BAIRRO) || '' }}${{ inputs.arquivo_rodando_imovel }}"
          
          echo "Executando: $CAMINHO_EXECUCAO"
          uv run $CAMINHO_EXECUCAO
        env:
          CIDADE_PASTA: ${{ inputs.cidade_pasta }}
          HEADLESS: ${{ inputs.headless }}
          MAX_CONCURRENCY_CHAVE: ${{ inputs.max_concurrency_chave }}
          MAX_CONCURRENCY_OLX: ${{ inputs.max_concurrency_olx }}
          MAX_CONCURRENCY: ${{ inputs.max_concurrency_zap }}
          CIDADE_LIMPEZA: ${{ inputs.cidade_limpeza }}
          MAX_CONCURRENCY_LOCALIZACAO: ${{ inputs.max_concurrency_localizacao }}
          BATCH_LIMPEZA: ${{ inputs.batch_limpeza }}
          TIPO_ASYNC: ${{ inputs.tipo_async }}
          CIDADE_LOCALIZACAO: ${{ inputs.cidade_localizacao }}
          ESTADO_LIMPEZA: ${{ inputs.estado_limpeza }}
          ESTADO_LOCALIZACAO: ${{ inputs.estado_localizacao }}
          BAIRRO : ${{ inputs.BAIRRO }}
          URL_TEMPLATE_VIVAREAL: ${{ inputs.URL_TEMPLATE_VIVAREAL }}
          URL_TEMPLATE_OLX: ${{ inputs.URL_TEMPLATE_OLX }}
          URL_TEMPLATE_ZAP: ${{ inputs.URL_TEMPLATE_ZAP }}
          URL_TEMPLATE_CHAVES: ${{ inputs.URL_TEMPLATE_CHAVES }}
          FILTRO_BAIRRO: ${{ inputs.FILTRO_BAIRRO }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ inputs.DATABRICKS_HOST }}
          LOCALIZAZAO_COMPLETA: ${{ inputs.LOCALIZAZAO_COMPLETA }}
          INCLUIR_TOPICOS: ${{ inputs.INCLUIR_TOPICOS }}

      - name: Commit e Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dados/
          git commit -m "Pipeline ${{ inputs.cidade_pasta}}: $(date +'%Y-%m-%d')" || echo "Nada para commitar"
          git pull --rebase --autostash -X ours origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}