name: Rodando Coleta Rio Janeiro Lagoa
on: 
  schedule:
    - cron: '0 16 25 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

jobs:
  coleta_leblon_chave_mao:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_lagoa_coleta_dados_chave_mao.py
      URL_TEMPLATE_CHAVES : "https://www.chavesnamao.com.br/imoveis-a-venda/rj-rio-de-janeiro/lagoa/leblon/?filtro=amin%3A{min}%2Camax%3A{max}&pg={pagina}"
      BAIRRO : lagoa
    
  coleta_leblon_olx_0_150:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_lagoa_coleta_dados_olx_0_150.py
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/estado-rj/rio-de-janeiro-e-regiao/zona-sul/lagoa?ss={min}&se={max}&o={pagina}"
      BAIRRO : lagoa

  coleta_leblon_olx_101_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_lagoa_coleta_dados_olx_151_infinito.py
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/estado-rj/rio-de-janeiro-e-regiao/zona-sul/lagoa?ss={min}&se={max}&o={pagina}"
      BAIRRO : lagoa
  
  coleta_leblon_zap:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_lagoa_coleta_dados_zap_imoveis.py
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/rj+rio-de-janeiro+zona-sul+lagoa/?onde=%2CRio+de+Janeiro%2CRio+de+Janeiro%2CZona+Sul%2CLagoa%2C%2C%2Cneighborhood%2CBR%3ERio+de+Janeiro%3ENULL%3ERio+de+Janeiro%3EZona+Sul%3ELagoa%2C-22.96182%2C-43.203077%2C&pagina={pagina}"
      BAIRRO : lagoa

  coleta_leblon_viva_real:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_lagoa_coleta_dados_viva_real.py
      URL_TEMPLATE_VIVAREAL: "https://www.vivareal.com.br/venda/rj/rio-de-janeiro/zona-sul/lagoa/?onde=%2CRio+de+Janeiro%2CRio+de+Janeiro%2CZona+Sul%2CLagoa%2C%2C%2Cneighborhood%2CBR%3ERio+de+Janeiro%3ENULL%3ERio+de+Janeiro%3EZona+Sul%3ELagoa%2C-22.96182%2C-43.203077%2C&pagina={pagina}"
      BAIRRO : lagoa
  
