name: Rodando Criando Indice Localizacao Imoveis Rio Janeiro Leblon
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Rio Janeiro Leblon"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_leblon_indice_localizacao.py
      BAIRRO : leblon