name: Rodando Limpeza Imoveis Rio Janeiro Tijuca
on:
  schedule:
      - cron: '0 21 30 1,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch:  

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_tijuca_limpando_dados.py
      cidade_limpeza: rio de janeiro
      cidade_localizacao: Rio de Janeiro
      estado_limpeza: rj
      estado_localizacao: RJ
      BAIRRO : tijuca
      FILTRO_BAIRRO : "tijuca"