name: Predicao Rio Janeiro Copacabana - Otimizando Melhores Modelos

on:
  workflow_run:
    workflows: ["Predicao Rio Janeiro Copacabana - Melhores Configuracoes Modelo"]
    types:
      - completed
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_predicao_rodando.yml
    with:
      cidade_pasta: rio_janeiro
      arquivo_rodando_imovel: rio_janeiro_otimizando_melhores_modelos.py
      bairro: copacabana
    secrets: inherit
