name: Predicao Sao Paulo Vila Andrade - Melhor Modelo Geral

on:
  workflow_run:
    workflows: ["Predicao Sao Paulo Vila Andrade - Otimizando Melhores Modelos"]
    types:
      - completed
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_predicao_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_melhor_modelo_geral.py
      bairro: vila-andrade
    secrets: inherit
