name: Rodando Coleta Viva Real Sao Paulo
on: 

    workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Sao Paulo"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel:  sao_paulo_coleta_dados_viva_real.py