name: Rodando Limpeza Imoveis Sao Paulo Jardins

on: 
  schedule:
    - cron: '0 9 17 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch: 

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_limpando_dados.py
      cidade_limpeza: sao paulo
      cidade_localizacao: Sao Paulo
      estado_limpeza: sp
      estado_localizacao: SP
      BAIRRO : jardins
      FILTRO_BAIRRO : "jardins"