name: Rodando Coleta Chave Mao Sao Paulo Pinheiros
on:
  schedule:
    - cron: '0 16 19 1,2,3,4,5,6,7,8,9,10,11,12 *'  # 09:00 no primeiro dia de cada mês
  workflow_dispatch:

jobs:
  coleta_chave_mao_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_pinheiros_coleta_dados_chave_mao_0_100.py
      URL_TEMPLATE_CHAVES : "https://www.chavesnamao.com.br/apartamentos-a-venda/sp-sao-paulo/pinheiros/?filtro=amin%3A{min}%2Camax%3A{max}&pg={pagina}"
      BAIRRO : pinheiros

  coleta_chave_mao_101_200:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_pinheiros_coleta_dados_chave_mao_101_200.py
      URL_TEMPLATE_CHAVES : "https://www.chavesnamao.com.br/apartamentos-a-venda/sp-sao-paulo/pinheiros/?filtro=amin%3A{min}%2Camax%3A{max}&pg={pagina}"
      BAIRRO : pinheiros

  coleta_chave_mao_201_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_pinheiros_coleta_dados_chave_mao_201_infinito.py
      URL_TEMPLATE_CHAVES : "https://www.chavesnamao.com.br/apartamentos-a-venda/sp-sao-paulo/pinheiros/?filtro=amin%3A{min}%2Camax%3A{max}&pg={pagina}"
      BAIRRO : pinheiros

  