name: Rodando Coleta Viva Real Sao Paulo Itaim Bibi
on: 
  workflow_run:
        workflows: ["Rodando Coleta Zap Imoveis Sao Paulo Itaim Bibi"]
        types:
            - completed
  workflow_dispatch:  

jobs:
  coleta_viva_real_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo/itaim-bibi
      arquivo_rodando_imovel: sao_paulo_itaim_bibi_coleta_dados_viva_real_0_100.py
      BAIRRO : itaim-bibi
      URL_TEMPLATE_VIVAREAL : "https://www.vivareal.com.br/venda/sp/sao-paulo/zona-sul/itaim-bibi/apartamento_residencial/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CItaim+Bibi%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EItaim+Bibi%2C-23.583748%2C-46.678074%2C&tipos=apartamento_residencial&pagina={pagina}"



  coleta_viva_real_101_200:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo/itaim-bibi
      arquivo_rodando_imovel: sao_paulo_itaim_bibi_coleta_dados_viva_real_101_200.py
      BAIRRO : itaim-bibi
      URL_TEMPLATE_VIVAREAL : "https://www.vivareal.com.br/venda/sp/sao-paulo/zona-sul/itaim-bibi/apartamento_residencial/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CItaim+Bibi%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EItaim+Bibi%2C-23.583748%2C-46.678074%2C&tipos=apartamento_residencial&pagina={pagina}"

  coleta_viva_real_201_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo/itaim-bibi
      arquivo_rodando_imovel: sao_paulo_itaim_bibi_coleta_dados_viva_real_201_infinito.py
      BAIRRO : itaim-bibi
      URL_TEMPLATE_VIVAREAL : "https://www.vivareal.com.br/venda/sp/sao-paulo/zona-sul/itaim-bibi/apartamento_residencial/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CItaim+Bibi%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EItaim+Bibi%2C-23.583748%2C-46.678074%2C&tipos=apartamento_residencial&pagina={pagina}"



  