name: Predicao Sao Paulo Moema - Otimizando Melhores Modelos

on:
  workflow_run:
    workflows: ["Predicao Sao Paulo Moema - Melhores Configuracoes Modelo"]
    types:
      - completed
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_predicao_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_otimizando_melhores_modelos.py
      bairro: moema
    secrets: inherit
