name: Predicao Sao Paulo Pinheiros - Melhores Configuracoes Modelo

on:
  workflow_run:
    workflows: ["Rodando Limpeza Imoveis Sao Paulo Pinheiros"]
    types:
      - completed
  workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_predicao_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_melhores_configuraoes_modelo.py
      bairro: pinheiros
    secrets: inherit
