name: Rodando Coleta Olx Sao Paulo Jardins
on: 
    workflow_run:
        workflows: ["Rodando Coleta Chave Mao Sao Paulo Jardins"]
        types:
            - completed
    workflow_dispatch:    

jobs:
  coleta_olx_0_50:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_0_50.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"


  coleta_olx_51_90:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_51_90.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"


  coleta_olx_91_130:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_91_130.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"


  coleta_olx_131_180:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_131_180.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"

      

  coleta_olx_181_300:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_181_300.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"

  
  coleta_olx_301_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_olx_301_infinito.py
      BAIRRO : jardins
      URL_TEMPLATE_OLX : "https://www.olx.com.br/imoveis/venda/apartamentos/estado-sp/sao-paulo-e-regiao/zona-sul/jardins?ss={min}&se={max}&o={pagina}"

  