name: Rodando Coleta Zap Imoveis Sao Paulo Vila Andrade
on: 
  workflow_run:
        workflows: ["Rodando Coleta Olx Sao Paulo Vila Andrade"]
        types:
            - completed
  workflow_dispatch:  

jobs:
  coleta_zap_imoveis_0_80:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_vila_andrade_coleta_dados_zap_imoveis_0_80.py
      BAIRRO : vila-andrade
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-sul+vl-andrade/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CVila+Andrade%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EVILA+ANDRADE%2C-23.631509%2C-46.736743%2C&pagina={pagina}"


  coleta_zap_imoveis_81_150:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_vila_andrade_coleta_dados_zap_imoveis_81_150.py
      BAIRRO : vila-andrade
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-sul+vl-andrade/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CVila+Andrade%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EVILA+ANDRADE%2C-23.631509%2C-46.736743%2C&pagina={pagina}"

  
  coleta_zap_imoveis_151_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_vila_andrade_coleta_dados_zap_imoveis_151_infinito.py
      BAIRRO : vila-andrade
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-sul+vl-andrade/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Sul%2CVila+Andrade%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Sul%3EVILA+ANDRADE%2C-23.631509%2C-46.736743%2C&pagina={pagina}"


  