name: Rodando Criando Indice Localizacao Imoveis Sao Paulo Vila Andrade
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Sao Paulo Vila Andrade"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_vila_andrade_indice_localizacao.py
      BAIRRO : vila-andrade