name: Rodando Criando Indice Localizacao Imoveis Sao Paulo Santana
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Sao Paulo Santana"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_santana_indice_localizacao.py
      BAIRRO : santana