name: Rodando Criando Indice Localizacao Imoveis Sao Paulo Pinheiros
on: 

    workflow_run:
        workflows: ["Rodando Limpeza Imoveis Sao Paulo Pinheiros"]
        types:
            - completed
    workflow_dispatch:

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_pinheiros_criando_indice_localizacao.py
      BAIRRO : pinheiros