name: Rodando Coleta Zap Imoveis Sao Paulo Jardins
on: 
  workflow_run:
        workflows: ["Rodando Coleta Olx Sao Paulo Jardins"]
        types:
            - completed
  workflow_dispatch:  

jobs:
  coleta_zap_imoveis_0_100:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_zap_imoveis_0_100.py
      BAIRRO : jardins
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-oeste+jardins/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Oeste%2CJardins%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Oeste%3EJardins%2C-23.573979%2C-46.660691%2C&pagina={pagina}"



  coleta_zap_imoveis_101_200:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_zap_imoveis_101_200.py
      BAIRRO : jardins
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-oeste+jardins/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Oeste%2CJardins%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Oeste%3EJardins%2C-23.573979%2C-46.660691%2C&pagina={pagina}"


   
  
  coleta_zap_imoveis_201_infinito:
    uses: ./.github/workflows/pipeline_cidade_rodando.yml
    with:
      cidade_pasta: sao_paulo
      arquivo_rodando_imovel: sao_paulo_jardins_coleta_dados_zap_imoveis_201_infinito.py
      BAIRRO : jardins
      URL_TEMPLATE_ZAP : "https://www.zapimoveis.com.br/venda/imoveis/sp+sao-paulo+zona-oeste+jardins/?onde=%2CS%C3%A3o+Paulo%2CS%C3%A3o+Paulo%2CZona+Oeste%2CJardins%2C%2C%2Cneighborhood%2CBR%3ESao+Paulo%3ENULL%3ESao+Paulo%3EZona+Oeste%3EJardins%2C-23.573979%2C-46.660691%2C&pagina={pagina}"


  